### ISSUE TITLE
Difficulty loading the resulting Arrow file

### ISSUE THREAD

**Issue by yurivish** [domoritz/csv2arrow#63] opened 2022-05-20 19:53 UTC
Hi Dominik, I found this very aptly named package when I googled "CSV to Arrow". 😄

I'm not yet sure what the issue is (or whether it has anything to do with your package!), but I'm having difficulty loading a particular arrow file resulting from your program and was wondering if this is a problem you've seen before. I haven't worked extensively with arrow files so maybe I've just done something obviously incorrect.

I made an Observable notebook here to illustrate the problem: https://observablehq.com/d/b428f10fec94e4b9

**Comment by domoritz** [comment] 2022-05-20 20:57
Arrow.js does not support compression so maybe that's the issue? I would try with a smaller file to see whether you can reproduce the issue. I would also try arrow 8 instead of whatever arrow version observable provides.

**Comment by yurivish** [comment] 2022-05-20 23:45
Pardon my ignorance, but I tried to follow your advice and am not sure I succeeded. The notebook above chronicles my adventures – I tried loading a smaller file in several ways using arrow 8, but none succeeded in returning a non-empty table. 

It seems the documentation is oriented towards Node use cases so it's possible I've misinterpreted the right way to load a table using `apache-arrow`.

I still think it's entirely possible that your library is functioning correctly here, though I also tried to the smaller table with the Julia programming language's Arrow library and that also did not succeed.

> Arrow.js does not support compression so maybe that's the issue? 

FWIW, the file size of the Arrow file is larger than the source CSV for both the large and small files.

**Comment by domoritz** [comment] 2022-05-21 05:34
Maybe try a different CSV file.

**Comment by yurivish** [comment] 2022-05-22 00:46
The same difficulty persists with a minimal CSV:

```bash
% echo "a,b,c\n1,2,3" > test.csv
% cat test.csv
a,b,c
1,2,3
% csv2arrow test.csv test.arrow
```

See the bottom of the notebook: https://observablehq.com/d/b428f10fec94e4b9

**Comment by domoritz** [comment] 2022-05-23 03:01
It looks like the schema is not being parsed correctly in this example (at least on my machine). Do you see the same issue? 

```
$ csv2arrow test.csv test.arrow -n
Schema:

{
  "fields": [
    {
      "name": "a",
      "nullable": false,
      "type": {
        "name": "utf8"
      },
      "children": []
    },
    {
      "name": "b",
      "nullable": false,
      "type": {
        "name": "utf8"
      },
      "children": []
    },
    {
      "name": "c\\n1",
      "nullable": false,
      "type": {
        "name": "utf8"
      },
      "children": []
    },
    {
      "name": "2",
      "nullable": false,
      "type": {
        "name": "utf8"
      },
      "children": []
    },
    {
      "name": "3",
      "nullable": false,
      "type": {
        "name": "utf8"
      },
      "children": []
    }
  ],
  "metadata": {}
}
```

**Comment by yurivish** [comment] 2022-05-23 03:05
Interesting, mine is different:

```yurivish@Compy ~ % csv2arrow test.csv test.arrow -n
Schema:

{
  "fields": [
    {
      "name": "a",
      "nullable": false,
      "type": {
        "name": "int",
        "bitWidth": 64,
        "isSigned": true
      },
      "children": []
    },
    {
      "name": "b",
      "nullable": false,
      "type": {
        "name": "int",
        "bitWidth": 64,
        "isSigned": true
      },
      "children": []
    },
    {
      "name": "c",
      "nullable": false,
      "type": {
        "name": "int",
        "bitWidth": 64,
        "isSigned": true
      },
      "children": []
    }
  ],
  "metadata": {}
}
```

The test.csv file contents are

```a,b,c
1,2,3

```

**Comment by domoritz** [comment] 2022-05-31 16:21
Huh, strange. I can't get it to work either. It doesn't look like we broke anything, though. Here is where I payed with it https://observablehq.com/d/dec13dcbe279c5ec. This need sot be investigated more.

**Comment by boudra** [comment] 2022-09-07 17:18
This might be the solution to the issue #85

**Comment by domoritz** [comment] 2022-09-08 00:39
Fixed in https://github.com/domoritz/csv2arrow/pull/85

**Closed by domoritz** 2022-09-08 00:39 UTC
